package org.core.enums;

public enum LogStatus {
    READY_EXTRACT,
    EXTRACTING_DATA,
    SUCCESS_EXTRACT,
    FAILURE_EXTRACT,
    READY_FILE,
    LOADING_STAGING,
    SUCCESS_STAGING,
    FAILURE_STAGING,
    READY_WAREHOUSE,
    LOADING_WAREHOUSE,
    TRANSFORMING_WAREHOUSE,
    SUCCESS_WAREHOUSE,
    FAILURE_WAREHOUSE,
    READY_DATAMART,
    TRANSFORMING_DATAMART,
    LOADING_DATAMART,
    SUCCESS_DATAMART,
    FAILURE_DATAMART

}
